POST http://localhost:5235/api/auth/register
Content-Type: application/json

{
  "Name": "Mariem",
  "LastName": "bj",
  "Email": "mariem@gmail.com",
  "Password": "mariem123",
  "Role": "Admin",
  "Direction": "Finance",
  "Fonction": "Direc",
  "Societe": "kjs",
  "Validateur1": "iyed@gmail.com",
  "Statut": "Active"
}